FROM alpine:latest AS builder

# --- Install vcpkg --- #
RUN apk --no-cache --upgrade add \
    build-base cmake ninja zip unzip curl git tar pkgconfig bash linux-headers gcompat perl ccache

WORKDIR /opt

RUN git clone https://github.com/microsoft/vcpkg.git

WORKDIR /opt/vcpkg

#RUN git checkout <COMMIT_HASH>

RUN ./bootstrap-vcpkg.sh

ENV VCPKG_ROOT=/opt/vcpkg
ENV VCPKG_BINARY_SOURCES="clear;files,/opt/vcpkg_cache,readwrite"
ENV PATH=$PATH:$VCPKG_ROOT

# --- Create Executable --- #

WORKDIR /app

COPY vcpkg/ .

RUN --mount=type=cache,target=/opt/vcpkg_cache \
    /opt/vcpkg/vcpkg install --triplet x64-linux

ENV CMAKE_CXX_COMPILER_LAUNCHER=ccache

COPY src/ ./src/

RUN cmake -B ./build -S ./src \
    -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake \
    -DVCPKG_TARGET_TRIPLET=x64-linux \
    -DVCPKG_INSTALLED_DIR=/app/vcpkg_installed \
    -G Ninja

RUN cmake --build build

# --- Create Final Container --- #
#FROM alpine:3.14

WORKDIR /wwwroot
#COPY --from=builder /app/build/WebAppDevKit ./
COPY  ./serverRoot/ ./

ENV PORT=80

EXPOSE $PORT

CMD ["../app/build/WebAppDevKit"]